### ISSUE TITLE
Not recording power data to file ?

### ISSUE THREAD

**Issue by qvanderlinden** [flowstatedev/ciq-runpower#2]
Hi,

I just installed Run Power on my Garmin Forerunner 935 and used it for a short test activity (less than 1 minute) to see if the connection with my Stryd power meter was working properly. During the activity, I could see the power metric updating on my watch screen but unfortunately when the activity was uploaded to Garmin Connect I could not see any power data. The activity was not uploaded the Stryd PowerCenter either, since there was no power data.

How can I turn on the recording of power data within the FIT file ?

Thanks in advance :-)

**Comment by flowstatedev** [comment]
Hey,

Thanks for the interest in Run Power. As noted in the [feature list](https://github.com/flowstatedev/ciq-runpower/wiki/Features), recording is not supported for 935, due to memory constraints. Currently, recording is supported on watches with more memory such as 645 Music and Fenix 5 Plus.

If I'm not mistaken, there is no comparable data field in the Garmin app store which gives you all the features of Run Power, as well as recording, because there simply isn't enough room for all those features on the 935 (and similar watches), which have half the memory (available to data fields) as 645 Music, and 1/4 the memory of Fenix 5 Plus. I would go as far to say that a similar data field in the store (sometimes compared to Run Power) requires you to have an F5+ to get what Run Power gives you for 935, and still doesn't support recording.

**However**, I am currently working on a new version of the app, Run Power+, which will free up memory for more features (e.g. on watches such as 935), by moving all the app settings from Garmin Connect to an external web app:
https://forums.garmin.com/forum/developers/connect-iq/connect-iq-showcase/1441455-run-power-move-settings-to-web-app-for-more-features

For now, I hope you will be okay with using Run Power and the Stryd data field concurrently, if you need recording.

**Comment by qvanderlinden** [comment]
Hey,

Thanks for you quick and detailed answer, I really appreciate it ! :-)

I will run Run Power and Stryd Power concurrently for now, thanks for the tip.

Have a nice weekend and thanks again,
Quentin

**Comment by flowstatedev** [comment]
No worries! I know that from the user’s POV, the limitations of the devices and the ecosystem aren’t always clear. But most Garmin watches have very little memory available for CIQ data fields. 

Any suggestions for improving the app are always welcome.

Have a good one,
Will
